import sqlite3
from pathlib import Path
from unittest.mock import MagicMock

import pandas as pd
import pytest

from savant.db import CSV_COLUMNS, init_db


@pytest.fixture
def tmp_db(tmp_path):
    db_path = tmp_path / "test.db"
    init_db(db_path)
    return db_path


@pytest.fixture
def sample_row():
    return {
        "pitch_type": "FF",
        "game_date": "2026-05-03",
        "release_speed": 95.0,
        "release_pos_x": -1.5,
        "release_pos_z": 5.8,
        "player_name": "Test Player",
        "batter": 123456,
        "pitcher": 654321,
        "events": "strikeout",
        "description": "swinging_strike",
        "spin_dir": None,
        "spin_rate_deprecated": None,
        "break_angle_deprecated": None,
        "break_length_deprecated": None,
        "zone": 5,
        "des": "Swinging Strike",
        "game_type": "R",
        "stand": "R",
        "p_throws": "R",
        "home_team": "NYY",
        "away_team": "BOS",
        "type": "S",
        "hit_location": None,
        "bb_type": None,
        "balls": 2,
        "strikes": 2,
        "game_year": 2026,
        "pfx_x": 0.5,
        "pfx_z": 1.2,
        "plate_x": 0.1,
        "plate_z": 2.5,
        "on_3b": None,
        "on_2b": None,
        "on_1b": None,
        "outs_when_up": 1,
        "inning": 5,
        "inning_topbot": "Top",
        "hc_x": None,
        "hc_y": None,
        "tfs_deprecated": None,
        "tfs_zulu_deprecated": None,
        "umpire": None,
        "sv_id": "260503_123456",
        "vx0": 5.0,
        "vy0": -130.0,
        "vz0": -3.0,
        "ax": -5.0,
        "ay": 25.0,
        "az": -30.0,
        "sz_top": 3.5,
        "sz_bot": 1.5,
        "hit_distance_sc": None,
        "launch_speed": None,
        "launch_angle": None,
        "effective_speed": 94.5,
        "release_spin_rate": 2400,
        "release_extension": 6.5,
        "game_pk": 745678,
        "fielder_2": 111111,
        "fielder_3": 222222,
        "fielder_4": 333333,
        "fielder_5": 444444,
        "fielder_6": 555555,
        "fielder_7": 666666,
        "fielder_8": 777777,
        "fielder_9": 888888,
        "release_pos_y": 55.0,
        "estimated_ba_using_speedangle": None,
        "estimated_woba_using_speedangle": None,
        "woba_value": None,
        "woba_denom": None,
        "babip_value": None,
        "iso_value": None,
        "launch_speed_angle": None,
        "at_bat_number": 10,
        "pitch_number": 5,
        "pitch_name": "4-Seam Fastball",
        "home_score": 3,
        "away_score": 2,
        "bat_score": 2,
        "fld_score": 3,
        "post_away_score": 2,
        "post_home_score": 3,
        "post_bat_score": 2,
        "post_fld_score": 3,
        "if_fielding_alignment": "Standard",
        "of_fielding_alignment": "Standard",
        "spin_axis": 180.0,
        "delta_home_win_exp": 0.05,
        "delta_run_exp": -0.1,
        "bat_speed": 70.0,
        "swing_length": 5.0,
        "estimated_slg_using_speedangle": None,
        "delta_pitcher_run_exp": 0.1,
        "hyper_speed": 95.0,
        "home_score_diff": 1,
        "bat_score_diff": -1,
        "home_win_exp": 0.65,
        "bat_win_exp": 0.35,
        "age_pit_legacy": 28,
        "age_bat_legacy": 26,
        "age_pit": 28,
        "age_bat": 26,
        "n_thruorder_pitcher": 2,
        "n_priorpa_thisgame_player_at_bat": 3,
        "pitcher_days_since_prev_game": 4,
        "batter_days_since_prev_game": 1,
        "pitcher_days_until_next_game": 5,
        "batter_days_until_next_game": 0,
        "api_break_z_with_gravity": 15.0,
        "api_break_x_arm": 3.0,
        "api_break_x_batter_in": -3.0,
        "arm_angle": 45.0,
        "attack_angle": 10.0,
        "attack_direction": 5.0,
        "swing_path_tilt": 30.0,
        "intercept_ball_minus_batter_pos_x_inches": 2.0,
        "intercept_ball_minus_batter_pos_y_inches": -1.0,
    }


@pytest.fixture
def sample_df(sample_row):
    return pd.DataFrame([sample_row])


@pytest.fixture
def mock_response_csv():
    header = ",".join(CSV_COLUMNS)
    row1 = ",".join([
        "FF", "2026-05-03", "95.0", "-1.5", "5.8",
        '"Test, Player"', "123456", "654321", "strikeout", "swinging_strike",
        "", "", "", "",
        "5", "Swinging Strike", "R", "R", "R", "NYY", "BOS",
        "S", "", "", "2", "2", "2026",
        "0.5", "1.2", "0.1", "2.5", "", "", "",
        "1", "5", "Top", "", "",
        "", "", "", "260503_123456",
        "5.0", "-130.0", "-3.0", "-5.0", "25.0", "-30.0",
        "3.5", "1.5", "", "", "",
        "94.5", "2400", "6.5", "745678",
        "111111", "222222", "333333", "444444", "555555",
        "666666", "777777", "888888", "55.0",
        "", "",
        "", "", "", "",
        "", "10", "5", "4-Seam Fastball",
        "3", "2", "2", "3",
        "2", "3", "2", "3",
        "Standard", "Standard", "180.0",
        "0.05", "-0.1", "70.0", "5.0",
        "", "0.1", "95.0",
        "1", "-1", "0.65", "0.35",
        "28", "26", "28", "26",
        "2", "3",
        "4", "1", "5", "0",
        "15.0", "3.0", "-3.0",
        "45.0", "10.0", "5.0", "30.0",
        "2.0", "-1.0",
    ])
    return f"{header}\n{row1}\n"
